namespace SavingsTracker.Data;

/// <summary>
/// Represents a transaction generated by a specific event or recurring trigger.
/// Useful for identifying automated entries or linked financial events.
/// </summary>
/// <param name="Name">The name or description of the triggered event.</param>
/// <param name="Amount">The specific monetary value assigned to this instance.</param>
/// <param name="Tag">A unique identifier or label used to group or filter these triggers.</param>
/// <param name="OriginalDate">The timestamp of the source event that initiated this transaction.</param>
public record TriggeredTransaction(
    string Name, 
    double Amount, 
    string Tag, 
    DateTime OriginalDate
);

